config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  
  # Add a user show page
  # get 'users/:id'
  # get 'users/index'
  # get '/user/:id' => "users#show:id"
  devise_for :users

  resources :users, only: [:show, :index ]

  resources :teams do
    post 'posts', to: 'posts#create'
    post  'userteams', to: 'userteams#create'
    # comment 'comments', to: 'comments#create'
    # resources :comments, only: [:create]
    collection {post :import }
    get "myteams/destroy"
  end

  resources :comments
  resources :posts
  resources :userteams
  # devise_for :users, controllers: { sessions: 'users/sessions' }

    
  get "/myteams" => "teams#myteams"
  get "/teams/myteams" => "teams#myteams"
  post  '/', to: 'userteams#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'users/index'
  # get 'users/:id'
  # get 'userteams/index'
  # get 'userteams/new'
  # get 'userteams/destroy'
end

 
 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :userteams 
  has_many :comments 
  has_many :teams, through: :userteams   
  
  
  def self.post_user_name(x)
    @post_user_name = User.find(x).email 
    @gud =  email_user_name(@post_user_name)
     
end

def self.email_user_name(x) 
   @email_user = x.split("@").first
    @email_user
end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  
  def index
    
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
     
  end


  def show
    
    @user = User.find(params[:id])
    puts @user.id
    @posts = Post.where(user_id: @user)
   
    # @team_id =  (Team.where(name: params[:id]).first).id
    # @team =  Team.where(name: params[:id]).first
    # if current_user
    #   @user_id = current_user.id
  end

end


#   <% if current_user  %>
# <%= form_with(model: @userteam, scope: "userteam" ) do |form|  %>
#      <%= form.hidden_field :team_id, :value => nflteam.id  %>
#      <%= form.hidden_field :user_id, :value => current_user.id %> 
#      <%= form.submit "+" ,id: 'addBttn'%>
#  <% end %>
# <% else %>
#  <%= link_to "+", new_user_session_path , id: 'addBttn'%>
# <% end %>  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
 
<div class="userMainPage">
    <% @users.each do |u| %>   
    <div class="usersBox"> 
        <div class="userAvatar">
            <table style="width:100%"> 
                <tr> 
                    <td>
                    </td>
                </tr>
            </table>
        </div>
        <div class="userLikeFollow">
            <table style="width:100%">
                <tr>
                    <td colspan="2" style="text-align:left"> 
                        <%= link_to User.email_user_name(u.email), user_path(u.id) %>
                    </td>
                    <td rowspan="2" class="userAdd"> + </td>
                </tr>
                <tr>
                    <td><%=Post.where(user_id: u.id).count%></td>
                    <td>88 Following</td>
                </tr>
            </table>
        </div> 
    </div> 
    <% end %> 

  

 

 </div> 

app/views/users/show.html.erb
 

<div class="userMain">
    <div class="userPageShowHeader" class="w3-card-4"> 
        
        <table style="width:100%" class="userShowMain">
             
            <tr> 
                <th rowspan="2" class="userPageAvatar">
                   pix go here
                </th>
                <td colspan="2" class="userName"> 
                       <%=User.email_user_name(@user.email) %> 
                </td>
                <td rowspan="2" class="showFollowAdd" >
                   +
              
                </td>
            </tr>
            <tr>
                <td class="showScore">
                    4 - 0
                </td>
                <td rowspan="2" class="showFollowers">
                     20000
                </td> 
            </tr> 
        </table> 
    </div> 

 
    <% if @posts %> 
        <div class="showUserPostMain">
        <% @posts.each do |p| %> 
        
            <div class="showUserPost">
                <div class="showUserPostspacer" >
                    <div class="UserPostTeamAvatar">
                    <%=  link_to  image_tag(Team.find(p.team_id).avatar, style:" width:80%" ), team_path(Team.find(p.team_id).name )   %>
                    </div>
                    
                    <div class="UserPost">
                    <%= p.post %> 
                    
                    </div> 
                    <div class="UserPostLikes">
                    <p> <%= time_ago_in_words(p.created_at) %>: Ago | 55 likes</p> 
                    </div>
                </div>       
            </div>  
        <% end %>
        </div>
        
    <% end %>
  

</div>   