config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  
  # Add a user show page
  # get 'users/:id'
  # get 'users/index'
  # get '/user/:id' => "users#show:id"
  devise_for :users

  resources :users, only: [:show, :index ]

  resources :teams do
    post 'posts', to: 'posts#create'
    post  'userteams', to: 'userteams#create'
    # comment 'comments', to: 'comments#create'
    # resources :comments, only: [:create]
    collection {post :import }
    get "myteams/destroy"
  end

  resources :comments
  resources :posts
  resources :userteams
  # devise_for :users, controllers: { sessions: 'users/sessions' }

    
  get "/myteams" => "teams#myteams"
  get "/teams/myteams" => "teams#myteams"
  post  '/', to: 'userteams#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'users/index'
  # get 'users/:id'
  # get 'userteams/index'
  # get 'userteams/new'
  # get 'userteams/destroy'
end

 
 

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :team
  has_many :comments, :dependent => :destroy
  validates_presence_of :post
  validates_length_of :post, :within => 2..300
  validates_presence_of :user_id

  # 
  has_one_attached :image
  # validate :correct_image_type

  # private 
  # def correct_image_type
  #       if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
  #           errors.add(:image, "must be img/png")
  #       elsif image.attached? == false
  #           errors.add(:image, "add image")
  #       end
  #   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.reverse
  end

#   # GET /posts/1
#   # GET /posts/1.json
#   def show
#   end

#   # GET /posts/new
#   def new
#     @post = Post.new
#   end

#   # GET /posts/1/edit
#   def edit
#   end


  # POST /posts
  # POST /posts.json
  # @current_user = current_user
   
  # puts @current_user
  # @post = @team.new(post_params)

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new( :post => @post )
  end
  
  def create  
    @user = (current_user).id  
    puts params.inspect  
     
    @post = Post.new(post_params)

  respond_to do |format|
    if @post.save
      format.html { redirect_to root_path, notice: 'Team was successfully created.' }
      format.json { render :show, status: :created, location: @post }
      format.js {render inline: "location.reload();" }
    else
      format.html { render :new }
      format.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end
end

private
  def post_params
    params.require(:post).permit(:post, :team_id, :user_id, :image ) 
  end
end

#   # PATCH/PUT /posts/1
#   # PATCH/PUT /posts/1.json
#   def update
#     respond_to do |format|
#       if @post.update(post_params)
#         format.html { redirect_to @post, notice: 'Post was successfully updated.' }
#         format.json { render :show, status: :ok, location: @post }
#       else
#         format.html { render :edit }
#         format.json { render json: @post.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /posts/1
#   # DELETE /posts/1.json
#   def destroy
#     @post.destroy
#     respond_to do |format|
#       format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_post
#       @post = Post.find(params[:id])
#     end

#     # Never trust parameters from the scary internet, only allow the white list through.
#     def post_params
#       @team_id

#       params.require(:post).permit(:post, :team_id, :user_id)
#     end
# end

# <%= image_tag(post.image, style:" width:40px" )%>




#    POST PAGE START

# <p id="notice"><%= notice %></p>

# <h1>Posts</h1>

# <table>
#   <thead>
#     <tr>
#       <th>Post</th>
#       <th>Team</th>
#       <th>User</th>
#       <th colspan="3"></th>
#     </tr>
#   </thead>

#   <tbody>
#     <% @posts.each do |post| %>
#       <tr>
#         <td><%= post.post %></td> 
#         <td><%= link_to 'Show', post %></td>
#         <td><%= link_to 'Edit', edit_post_path(post) %></td>
#         <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
#       </tr>
#     <% end %>
#   </tbody>
# </table>

# <br>

# <%= link_to 'New Post', new_post_path %>

#    POST PAGE END

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
 <%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post %>
  </div> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="allPostMain"> 

    <div class="contentHeader">
        <div class="myteamsWatchlist" id="postmyWatchlist">
          <h4>Watchlist<h4>
        </div>
        <div class="myteamsAll" id="postAllTeams">
          <h4>All<h4>
        </div>
        <div class="myteamsTrending" id="postTrendingTeams">
          <h4>Trending<h4>
        </div>
    </div>
 

<div class="watchlistCommentDiv">  
 <% @posts.each do |post| %>
    <div class="eachPost"> 
   
        <ul class="eachPostUl">
            <li class="userAvatarPost">
                <div class="userAvatarTimeDiv">
                    <table style="width:100%"> 
                        <tr>
                            <th rowspan="2" class="showUserAvatar">
                                <%= image_tag(post.image, style:" width:100%" )%>
                            </th>
                            <td class="userName">
                            <%= link_to User.post_user_name(post.user_id) , user_path(post.user_id) %>
                                
                            </td>
                            <td rowspan="2" class="userPostFollow">
                                <h1> + <h1>
                            </td>
                        </tr>
                        <tr>
                            <td class="postTime" >
                                <%= time_ago_in_words(post.created_at) %>: Ago
                            </td> 
                        </tr>
                    </table>
                </div>
                <div class="imageVideoPost">
                    <%= image_tag(post.image, style:" width:100%" )%>
                </div>
                <div class="textPost">
                   <%=   %>:  <%= post.post %>     
                </div>
                <div class="likeCommentBar">
                    <table style="width:100%">
                        <tr> 
                            <td class="postLikesicon"> 
                                x
                            </td>
                            <td class="postLikes"> 
                                5k likes
                            </td>
                            <td class="postComments" id="postComments">
                                5 comments
                            </td> 
                            <td class="postReply" onclick="myshow(this)">
                                reply
                            </td>  
                        </tr>  
                    </table>
                </div>
 
               
                <div class="commentReplyInput" id="postCommentReplyInput">
                    <div class="replySpacer">
                        <%= form_with model:  @comment do |f| %> 
                            <%= f.text_field :comment, placeholder: "Write a comment...", id: "commentInput"  %>
                            <%= f.hidden_field :post_id, :value => post.id %>
                            <%= f.hidden_field :user_id, :value => @user_id %>
                            <%=f.submit "reply"   %> 
                        <% end %>
                    </div>
                </div>
                <div class="postReplyComments" id="postPageReplyComments">
                <div class="replyComments"  >
                <% post.comments.each do |c| %>
                    <table style="width:100%" >
                        <tr>
                            <th rowspan="2" class="replyAvatar">
                                <%=   %> 

                            </th>
                            <td colspan="2" class="replyText" >
                                <%= c.comment %>
                            </td> 
                        </tr>
                        <tr>
                            <td class="replyTextTime">
                                <%= time_ago_in_words(c.created_at) %>: Ago | 55 likes
                            </td>
                            <td class="replyTextLikes">
                                 
                            </td> 
                        </tr>
                    </table>
                    <% end %>
                    </div>
                </div>
                </li>    
            </ul>
            
        </div>
    <% end %>
</div> 



<div class="allCommentDiv">  
 <% @posts.each do |post| %>
    <div class="eachPost"> 
   
        <ul class="eachPostUl">
            <li class="userAvatarPost">
                <div class="userAvatarTimeDiv">
                    <table style="width:100%"> 
                        <tr>
                            <th rowspan="2" class="showUserAvatar">
                                <%= image_tag(post.image, style:" width:100%" )%>
                            </th>
                            <td class="userName">
                            <%= link_to User.post_user_name(post.user_id) , user_path(post.user_id) %>
                                
                            </td>
                            <td rowspan="2" class="userPostFollow">
                                <h1> + <h1>
                            </td>
                        </tr>
                        <tr>
                            <td class="postTime" >
                                <%= time_ago_in_words(post.created_at) %>: Ago
                            </td> 
                        </tr>
                    </table>
                </div>
                <div class="imageVideoPost">
                    <%= image_tag(post.image, style:" width:100%" )%>
                </div>
                <div class="textPost">
                   <%=   %>:  <%= post.post %>     
                </div>
                <div class="likeCommentBar">
                    <table style="width:100%">
                        <tr> 
                            <td class="postLikesicon"> 
                                x
                            </td>
                            <td class="postLikes"> 
                                5k likes
                            </td>
                            <td class="postComments" id="postComments">
                                5 comments
                            </td> 
                            <td class="postReply" onclick="myshow(this)">
                                reply
                            </td>  
                        </tr>  
                    </table>
                </div>

               
                <div class="commentReplyInput" id="postCommentReplyInput">
                    <div class="replySpacer">
                        <%= form_with model:  @comment do |f| %> 
                            <%= f.text_field :comment, placeholder: "Write a comment...", id: "commentInput"  %>
                            <%= f.hidden_field :post_id, :value => post.id %>
                            <%= f.hidden_field :user_id, :value => @user_id %>
                            <%=f.submit "reply"   %> 
                        <% end %>
                    </div>
                </div>
                <div class="postReplyComments" id="postPageReplyComments">
                <div class="replyComments"  >
                <% post.comments.each do |c| %>
                    <table style="width:100%" >
                        <tr>
                            <th rowspan="2" class="replyAvatar">
                                <%=   %> 

                            </th>
                            <td colspan="2" class="replyText" >
                                <%= c.comment %>
                            </td> 
                        </tr>
                        <tr>
                            <td class="replyTextTime">
                                <%= time_ago_in_words(c.created_at) %>: Ago | 55 likes
                            </td>
                            <td class="replyTextLikes">
                                 
                            </td> 
                        </tr>
                    </table>
                    <% end %>
                    </div>
                </div>
                </li>    
            </ul>
            
        </div>
    <% end %>
</div> 

app/views/posts/index.js.erb
  function myshow(x) {
        alert("Row index is: " );
    }

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', root_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>

<p>
  <strong>Team:</strong>
  <%= @post.team %>
</p>
 

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>